<?php
// Centralized Database of Tyre Products
$products_db = [
    [
        'id' => 1,
        'brand' => 'Goodyear',
        'brand_label' => 'Goodyear Tyres',
        'brand_logo' => 'assets/image/brand-logo/goodyear.webp',
        'model' => 'Ducaro Hi-Miler Tubeless',
        'type' => 'Tubeless',
        'width' => '145',
        'ratio' => '80',
        'diameter' => 'R12',
        'size_label' => '145/80 R12',
        'image' => 'assets/image/product.png',
        'price' => 3120,
        'original_price' => 3220,
        'save_amount' => 100,
        'discount_pct' => '15% OFF',
        'rating' => 4.9,
        'reviews' => 128,
        'warranty' => '5 Yr Warranty',
        'sale' => true,
        'suitable_for' => 'Maruti Alto, Wagon R, Hyundai Santro'
    ],
    [
        'id' => 2,
        'brand' => 'Bridgestone',
        'brand_label' => 'Bridgestone Tyres',
        'brand_logo' => 'assets/image/brand-logo/bridgestone.webp',
        'model' => 'Turanza T005 Premium',
        'type' => 'Tubeless',
        'width' => '185',
        'ratio' => '65',
        'diameter' => 'R15',
        'size_label' => '185/65 R15',
        'image' => 'assets/image/product-1.png',
        'price' => 5450,
        'original_price' => 6400,
        'save_amount' => 950,
        'discount_pct' => '15% OFF',
        'rating' => 4.9,
        'reviews' => 215,
        'warranty' => '5 Yr Warranty',
        'sale' => true,
        'suitable_for' => 'Maruti Swift, Dzire, Baleno, Hyundai i20'
    ],
    [
        'id' => 3,
        'brand' => 'Apollo',
        'brand_label' => 'Apollo Tyres',
        'brand_logo' => 'assets/image/brand-logo/apollotyres.webp',
        'model' => 'Alnac 4G Luxury',
        'type' => 'Tubeless',
        'width' => '195',
        'ratio' => '65',
        'diameter' => 'R15',
        'size_label' => '195/65 R15',
        'image' => 'assets/image/product.png',
        'price' => 4850,
        'original_price' => 5500,
        'save_amount' => 650,
        'discount_pct' => '12% OFF',
        'rating' => 4.8,
        'reviews' => 94,
        'warranty' => '5 Yr Warranty',
        'sale' => true,
        'suitable_for' => 'Honda City, Hyundai Verna, Skoda Slavia'
    ],
    [
        'id' => 4,
        'brand' => 'CEAT',
        'brand_label' => 'CEAT Tyres',
        'brand_logo' => 'assets/image/brand-logo/ceat.webp',
        'model' => 'SecuraDrive High Grip',
        'type' => 'Tubeless',
        'width' => '195',
        'ratio' => '60',
        'diameter' => 'R15',
        'size_label' => '195/60 R15',
        'image' => 'assets/image/product-1.png',
        'price' => 4420,
        'original_price' => 4950,
        'save_amount' => 530,
        'discount_pct' => '11% OFF',
        'rating' => 4.7,
        'reviews' => 82,
        'warranty' => '5 Yr Warranty',
        'sale' => true,
        'suitable_for' => 'Tata Altroz, Honda Amaze, Ford EcoSport'
    ],
    [
        'id' => 5,
        'brand' => 'MRF',
        'brand_label' => 'MRF Tyres',
        'brand_logo' => 'assets/image/brand-logo/mrf.webp',
        'model' => 'ZVTV Long Life',
        'type' => 'Tubeless',
        'width' => '165',
        'ratio' => '70',
        'diameter' => 'R14',
        'size_label' => '165/70 R14',
        'image' => 'assets/image/product.png',
        'price' => 3890,
        'original_price' => 4300,
        'save_amount' => 410,
        'discount_pct' => '10% OFF',
        'rating' => 4.8,
        'reviews' => 110,
        'warranty' => '5 Yr Warranty',
        'sale' => true,
        'suitable_for' => 'Nissan Micra, Datsun Go, Renault Kwid'
    ],
    [
        'id' => 6,
        'brand' => 'Michelin',
        'brand_label' => 'Michelin Tyres',
        'brand_logo' => 'assets/image/brand-logo/michelin.webp',
        'model' => 'Primacy 4 ST Silent',
        'type' => 'Tubeless',
        'width' => '215',
        'ratio' => '60',
        'diameter' => 'R16',
        'size_label' => '215/60 R16',
        'image' => 'assets/image/product-1.png',
        'price' => 9150,
        'original_price' => 10200,
        'save_amount' => 1050,
        'discount_pct' => '10% OFF',
        'rating' => 5.0,
        'reviews' => 205,
        'warranty' => '6 Yr Warranty',
        'sale' => true,
        'suitable_for' => 'Toyota Innova Crysta, Maruti Brezza, Hyundai Venue'
    ],
    [
        'id' => 7,
        'brand' => 'JK Tyre',
        'brand_label' => 'JK Tyre',
        'brand_logo' => 'assets/image/brand-logo/jktyre.webp',
        'model' => 'UX Royale Comfort',
        'type' => 'Tubeless',
        'width' => '175',
        'ratio' => '65',
        'diameter' => 'R14',
        'size_label' => '175/65 R14',
        'image' => 'assets/image/product.png',
        'price' => 3650,
        'original_price' => 4100,
        'save_amount' => 450,
        'discount_pct' => '11% OFF',
        'rating' => 4.6,
        'reviews' => 67,
        'warranty' => '5 Yr Warranty',
        'sale' => true,
        'suitable_for' => 'Tata Tiago, Maruti Celerio, Honda Brio'
    ],
    [
        'id' => 8,
        'brand' => 'Yokohama',
        'brand_label' => 'Yokohama Tyres',
        'brand_logo' => 'assets/image/brand-logo/yokohama.webp',
        'model' => 'Earth-1 E400 All-Weather',
        'type' => 'Tubeless',
        'width' => '185',
        'ratio' => '70',
        'diameter' => 'R14',
        'size_label' => '185/70 R14',
        'image' => 'assets/image/product-1.png',
        'price' => 4600,
        'original_price' => 5100,
        'save_amount' => 500,
        'discount_pct' => '10% OFF',
        'rating' => 4.9,
        'reviews' => 142,
        'warranty' => '5 Yr Warranty',
        'sale' => true,
        'suitable_for' => 'Maruti Swift, Ritz, Hyundai i10 Grand'
    ],
    [
        'id' => 9,
        'brand' => 'Goodyear',
        'brand_label' => 'Goodyear Tyres',
        'brand_logo' => 'assets/image/brand-logo/goodyear.webp',
        'model' => 'Assurance TripleMax 2',
        'type' => 'Tubeless',
        'width' => '205',
        'ratio' => '65',
        'diameter' => 'R16',
        'size_label' => '205/65 R16',
        'image' => 'assets/image/product.png',
        'price' => 6850,
        'original_price' => 7600,
        'save_amount' => 750,
        'discount_pct' => '10% OFF',
        'rating' => 4.8,
        'reviews' => 89,
        'warranty' => '5 Yr Warranty',
        'sale' => true,
        'suitable_for' => 'Hyundai Creta, Kia Seltos, Maruti Grand Vitara'
    ],
    [
        'id' => 10,
        'brand' => 'MRF',
        'brand_label' => 'MRF Tyres',
        'brand_logo' => 'assets/image/brand-logo/mrf.webp',
        'model' => 'Nylogrip Plus Heavy',
        'type' => 'Tubetype',
        'width' => '145',
        'ratio' => '80',
        'diameter' => 'R12',
        'size_label' => '145/80 R12 Tube',
        'image' => 'assets/image/product-1.png',
        'price' => 2850,
        'original_price' => 3150,
        'save_amount' => 300,
        'discount_pct' => '10% OFF',
        'rating' => 4.7,
        'reviews' => 74,
        'warranty' => '3 Yr Warranty',
        'sale' => true,
        'suitable_for' => 'Maruti 800, Omni, Commercial Cargo'
    ],
    [
        'id' => 11,
        'brand' => 'Apollo',
        'brand_label' => 'Apollo Tyres',
        'brand_logo' => 'assets/image/brand-logo/apollotyres.webp',
        'model' => 'Amazer 4G Life Mileage',
        'type' => 'Tubeless',
        'width' => '155',
        'ratio' => '80',
        'diameter' => 'R13',
        'size_label' => '155/80 R13',
        'image' => 'assets/image/product.png',
        'price' => 3450,
        'original_price' => 3800,
        'save_amount' => 350,
        'discount_pct' => '9% OFF',
        'rating' => 4.8,
        'reviews' => 98,
        'warranty' => '5 Yr Warranty',
        'sale' => true,
        'suitable_for' => 'Hyundai Santro, Maruti Wagon R, Zen'
    ],
    [
        'id' => 12,
        'brand' => 'CEAT',
        'brand_label' => 'CEAT Tyres',
        'brand_logo' => 'assets/image/brand-logo/ceat.webp',
        'model' => 'Milaze X3 City',
        'type' => 'Tubetype',
        'width' => '155',
        'ratio' => '70',
        'diameter' => 'R13',
        'size_label' => '155/70 R13 Tube',
        'image' => 'assets/image/product-1.png',
        'price' => 3100,
        'original_price' => 3400,
        'save_amount' => 300,
        'discount_pct' => '9% OFF',
        'rating' => 4.6,
        'reviews' => 53,
        'warranty' => '3 Yr Warranty',
        'sale' => true,
        'suitable_for' => 'Maruti Alto K10, Hyundai Eon'
    ]
];
